language: generic
sudo: false
dist: trusty
branches:
  only:
  - master
  - "/^[0-9].*?-[0-9]{8}$/"
addons:
  apt:
    packages:
    - mingw-w64
    - curl
    - gettext
    - jq
    - git
    - p7zip-full
script:
- "./build"
deploy:
  provider: releases
  file: mk.exe
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  verbose: true
  on:
    tags: true
env:
<<<<<<< HEAD
  secure: mQvAYhQ1iW4Ma1tFz9oMak2aciC28RbwiCsho7XfsH3DHeo1fEWJZPoM3fMVG12iUPTpKNprnjpE+tc8sJFBpNDDLgzSd4TLd15NFE/BSuttw5Qeeg6XKC5erwSbGgvSOMJAv+mSFO1R3m7dAzz6we7nyLCgQAFdtgkXZkYjXimuZKO64KcUaDwpeALY6SJf0ufk6cCvbuR+9oxqT/8RKeWQN8DLyJQS7lav1/YlU5+YRKkq0PFfafu+/XoH+FojPQcKeoiyIjuqsCGeGM3TGC+MA4pXwnYex93vd/hdV/BuKcmkJntZO5OsCEHsZ26bkNjxY3iaXlbZYI99haMkOb8GxTfrR3sagkhNud59DSbx8KM8sjoh3MBca3dTxPtCfD3MwhZtGHGMC0AThop7vzWqDOG3iqLE6KBYw438WPlIyW6JMXxZ6QWojBND42VEeLP5V1Iuup4xyd6oknbb5jwl9RxMJ0zzvuCv40/S9+fPbQbk+EA9J3gkvcN9Xmf1CMbMZpzhXdIhFte9J/og4hmAxLcbNZQrPU032OtFXyiO4VXIH+5HLPUhV1EhDG4SbXTWQVMxH3nKpk3pxSLIdMtVODxsmB5Q6YDkZuVaa+0v9CzAFtawCbjkR0GmUTLQKvuerWTblUgo9FVa62CtcAeLABbYL0T7Y+uEfQTqSGc=
=======
  secure: KUHamdL2e+nPJIT87JG+XQAAXIHD3cQcooK8NH59PvpiYOyYfA0pvEI++plQYOqWc+hX4orfMppdkrlozqdZcQvbEBzZ/7ot6sW0rE3EqqHwDE2Y1ENQCtR478YwYQLy1MakHWBBKDXJYEJ3LIZhKxMh6sOK+/QUQkPkrMkZaE4rIdImAdiCKzN8VGoDSmsAByFH9Fkw9D+zflnCn0Nfgn/55JwLaWABzEMmlnja0LyYP1ka65NSMzcGhk6gMuBoZc8TRn5NQrJzw/QkNLfpqJFUBSwwiO8VnbPKlL0Rb4FRzRCtL65Va3CHJvUBgz6ZGyUTYzzkTe/SMkl7KFT73Q6S8GcFz3NPVhsPVGUSZ1El+yd+m/a8KMBMYIxHRCpkJOzV7I5nsbjqr9cozjnf5c0KFqBASgC4cQI4GMFp6T2R5qgfHa3rhXvejIYTX821E1WHAl7XOv/LdWGG6GyvA6u7Rfb3q2jm233dbeMFSNA3n5C8clZgAhn+FDT6GC71wAdDLG9AohRfrI2d2T3OCLTbdYFIFCBmjdQq9YeRHQwTOgzmAfnkIH8wIFpP21kfZOm883fRMQz+SCi5YZ3QBlUvp9JbWsgnQ8drgoc4WAYtUebfRT5s5eUsC/EQhWwuymOE4S/DVgCzU5Uawuggkowe8xUBCdv0MYD532n84Ds=
>>>>>>> 2dc4452b4187ad064cefc9442d0aaea16f85b386
