language: generic
sudo: false
dist: trusty
branches:
  only:
  - master
  - "/^[0-9].*?-[0-9]{8}$/"
addons:
  apt:
    packages:
    - mingw-w64
    - curl
    - gettext
    - jq
    - git
    - p7zip-full
script:
- "./build"
deploy:
  provider: releases
  file: mk.exe
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  verbose: true
  on:
    tags: true
env:
  secure: mQvAYhQ1iW4Ma1tFz9oMak2aciC28RbwiCsho7XfsH3DHeo1fEWJZPoM3fMVG12iUPTpKNprnjpE+tc8sJFBpNDDLgzSd4TLd15NFE/BSuttw5Qeeg6XKC5erwSbGgvSOMJAv+mSFO1R3m7dAzz6we7nyLCgQAFdtgkXZkYjXimuZKO64KcUaDwpeALY6SJf0ufk6cCvbuR+9oxqT/8RKeWQN8DLyJQS7lav1/YlU5+YRKkq0PFfafu+/XoH+FojPQcKeoiyIjuqsCGeGM3TGC+MA4pXwnYex93vd/hdV/BuKcmkJntZO5OsCEHsZ26bkNjxY3iaXlbZYI99haMkOb8GxTfrR3sagkhNud59DSbx8KM8sjoh3MBca3dTxPtCfD3MwhZtGHGMC0AThop7vzWqDOG3iqLE6KBYw438WPlIyW6JMXxZ6QWojBND42VEeLP5V1Iuup4xyd6oknbb5jwl9RxMJ0zzvuCv40/S9+fPbQbk+EA9J3gkvcN9Xmf1CMbMZpzhXdIhFte9J/og4hmAxLcbNZQrPU032OtFXyiO4VXIH+5HLPUhV1EhDG4SbXTWQVMxH3nKpk3pxSLIdMtVODxsmB5Q6YDkZuVaa+0v9CzAFtawCbjkR0GmUTLQKvuerWTblUgo9FVa62CtcAeLABbYL0T7Y+uEfQTqSGc=
